FROM golang:latest

#RUN apk update && apk upgrade && apk add --no-cache git

WORKDIR ./src

COPY ./src/api .

COPY ./src/go.mod .
COPY ./src/go.sum .
RUN go mod download

RUN GOOS=linux go build -o ./out/minitwit

EXPOSE 8081

CMD ["./out/minitwit-api"]