version: '3.3'
services: 
    minitwit:
        image: minitwit:latest
        build: .
        ports:
            - "8080:8080"
        restart: always
        networks: 
            - minitwit
networks: 
    minitwit: