version: '3.3'
services: 
    minitwit:
        image: minitwit:latest
        build: .
        ports:
            - "8080:8080"
            - "9090:9090"
        restart: always
        networks: 
            - main
networks: 
    main: