FROM golang:latest

#RUN apk update && apk upgrade && apk add --no-cache git

WORKDIR ./program

COPY ./program .

COPY ./program/go.mod .
COPY ./program/go.sum .
RUN go mod download

RUN GOOS=linux go build -o ./out/minitwit

EXPOSE 8080

CMD ["./out/minitwit"]