version: '3.3'
networks: 
    minitwit:
services: 
  minitwitimage:
    image: nannamarcher/minitwitimage
    container_name: minitwit
    networks:
      - minitwit
    ports:
        - '8080:8080'
        - '9090:9090'
