version: '3.3'
networks: 
    minitwit:
services: 
  minitwitimage:
    image: ***REMOVED***/minitwitimage
    container_name: minitwit
    networks:
      - minitwit
    ports:
        - '5000:5000'
        - '9090:9090'
