name: Go

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
    - dev

jobs:

  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.8
    
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        docker --version

    - name: Build API
      working-directory: ./api
      run: go build 
      
    - name: Build program
      working-directory: ./program
      run: go build 

    - name: Run vet & lint
      run: |
        go vet ./...
        golint ./...
        
    - uses: docker/build-push-action@v1
    - name: build and push docker
      run: |
        echo "LOGIN"
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        echo "BUILD"
        docker build -t ${DOCKER_USERNAME}/minitwitimage:latest . -f Dockerfile-program
        docker build -t ${DOCKER_USERNAME}/minitwitapi:latest . -f Dockerfile-api
        echo "PUSH"
        docker push ${DOCKER_USERNAME}/minitwitimage:latest
        docker push ${DOCKER_USERNAME}/minitwitapi:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: before script
      uses: matheusvanzan/sshpass-action@v2
      with:
        MT_SERVER: ${{ secrets.SERVER_HOST }}
        MT_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE: ${{ secrets.SSH_PASS }}
        run: |
          export SSHPASS=${SSH_PRIVATE}
          sshpass -e scp -o "StrictHostKeyChecking no" remote_files/docker-compose.yml ${MT_USER}@${MT_SERVER}:/vagrant/
          sshpass -e scp -o "StrictHostKeyChecking no" remote_files/prometheus.yml ${MT_USER}@${MT_SERVER}:/vagrant/
          sshpass -e scp -o "StrictHostKeyChecking no" remote_files/filebeat.yml ${MT_USER}@${MT_SERVER}:/vagrant/
          sudo chown root filebeat.yml 
          sudo chmod go-w filebeat.yml
    - uses: actions/github-script@v4
      with:
        script: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /vagrant && \
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} > .env && \
          docker-compose down && \
          docker-compose pull && \
          docker-compose up -d"
    

  
  
  
  
  
  







