name: Report to PDF

on:
    push:
        branches:
          - reportsetup

jobs:
    convert:
        name: Build PDF
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: baileyjm02/markdown-to-pdf@v1
            with:
              input_dir: report
              output_dir: report/build
              images_dir: report/images
              image_import: ./images
              build_html: false
          - uses: actions/upload-artifact@v1
            with:
              name: report
              path: report/build
