name: Report to PDF

on:
  push:
    branches:
      - master  
    paths:
      - 'report/report.md'

jobs:
  convert:
    name: Create report PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert markdown to PDF
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: report
          output_dir: report/build
          images_dir: report/images
          image_import: report/images
          build_html: false
      - name: Commit PDF
        run: |
          git config --local user.email "nanm@itu.dk"
          git config --local user.name "NannaMarcher"
          cd report/build
          git add report.pdf
          git commit -m "updated report pdf"
      - name: Push report changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Upload PDF
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report/build
