name: Report to PDF

on:
  push:
    branches: 
    - reportsetup

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: convert md to pdf
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: report
          output_dir: report/build
          images_dir: report/images
          image_import: ./images
          build_html: false
      - name: commit pdf
        run: |
          git config --local user.email "nanm@itu.dk"
          git config --local user.name "NannaMarcher"
          cd report/build
          git add report.pdf
          git commit -m "updated report pdf"
      - name: push report changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: reportsetup
      - uses: actions/upload-artifact@v1
        with:
          name: report
          path: report/build
